/**
 *  PHOTOUPLOAD 스키마
 */


CREATE TABLE PHOTOUPLOAD(
             FILEID    NUMBER PRIMARY KEY
            ,BID       NUMBER
            ,ACCOUNTID VARCHAR2(50) 
            ,UUIDNAME  VARCHAR2(50)  NOT NULL
            ,FILENAME  VARCHAR2(200) NOT NULL
            ,LOCATION  VARCHAR2(500) NOT NULL
            ,URL       VARCHAR2(500) NOT NULL 
            ,FILESIZE  NUMBER DEFAULT(0)
            ,FILETYPE  VARCHAR2(200) NOT NULL
            ,CONSTRAINT PHOTOUPLOAD_BID_FK FOREIGN KEY(BID) REFERENCES BOARD(BID) ON DELETE CASCADE
            ,CONSTRAINT PHOTOUPLOAD_ACCOUNTID_FK FOREIGN KEY(ACCOUNTID) REFERENCES ACCOUNT(ACCOUNTID) ON DELETE CASCADE
);

CREATE SEQUENCE PHOTOUPLOAD_SEQ NOCACHE;

SELECT * FROM PHOTOUPLOAD;
DROP TABLE PHOTOUPLOAD;

-- BID_FK도 ON DLETE CASCADE 추가 해야됨 9.24


-- 테이블을 다시 만들지 않고 해당 제약조건만 수정하는 쿼리

-- 1. 아래 쿼리로 해당 제약조건을 삭제한 후
ALTER TABLE PHOTOUPLOAD DROP CONSTRAINT PHOTOUPLOAD_ACCOUNTID_FK;
ALTER TABLE PHOTOUPLOAD DROP CONSTRAINT PHOTOUPLOAD_BID_FK;

-- 2. ON DELETE CASCADE를 적용시킨 제약조건을 다시 설정

ALTER TABLE PHOTOUPLOAD 
ADD CONSTRAINT PHOTOUPLOAD_ACCOUNTID_FK
FOREIGN KEY (ACCOUNTID) 
REFERENCES ACCOUNT (ACCOUNTID) 
ON DELETE CASCADE;

ALTER TABLE PHOTOUPLOAD 
ADD CONSTRAINT PHOTOUPLOAD_BID_FK
FOREIGN KEY (BID) 
REFERENCES BOARD (BID) 
ON DELETE CASCADE;

-- 3. 잘 설정되었는지 확인
SELECT *
  FROM USER_CONSTRAINTS
 WHERE TABLE_NAME = 'PHOTOUPLOAD';
