/**
 *  CHAT 스키마
 */

CREATE TABLE CHAT(
             ACCOUNTID  VARCHAR2(50)
            ,READCHECK  VARCHAR2(1) CHECK(READCHECK IN('Y','N'))
            ,CONTENT    VARCHAR2(1000)
            ,CREATEDATE DATE DEFAULT(SYSDATE)
            ,FILENAME   VARCHAR2(200)
            ,FILESIZE   NUMBER
            ,FILETYPE   VARCHAR2(200)
            ,CONSTRAINT CHAT_ACCOUNTID_FK FOREIGN KEY(ACCOUNTID) REFERENCES ACCOUNT(ACCOUNTID) ON DELETE CASCADE
);

SELECT * FROM CHAT;
DROP TABLE CHAT;


-- 테이블을 다시 만들지 않고 해당 제약조건만 수정하는 쿼리

-- 1. 아래 쿼리로 해당 제약조건을 삭제한 후
ALTER TABLE CHAT DROP CONSTRAINT CHAT_ACCOUNTID_FK;
-- 2. ON DELETE CASCADE를 적용시킨 제약조건을 다시 설정
ALTER TABLE CHAT 
ADD CONSTRAINT CHAT_ACCOUNTID_FK
FOREIGN KEY (ACCOUNTID) 
REFERENCES ACCOUNT (ACCOUNTID) 
ON DELETE CASCADE;
-- 3. 잘 설정되었는지 확인
SELECT *
  FROM USER_CONSTRAINTS
 WHERE TABLE_NAME = 'CHAT';
