/**
 *  BOARD 스키마
 */

-- 09.19 FK 삭제 가능하도록 ON DELETE CASCADE 처리
CREATE TABLE BOARD(
             BID        NUMBER PRIMARY KEY
            ,ACCOUNTID  VARCHAR2(50)
            ,BTITLE     VARCHAR2(300) NOT NULL
            ,BCONTENT   VARCHAR2(1000) NOT NULL
            ,CREATEDATE DATE DEFAULT(SYSDATE)
            ,VIEWCNT    NUMBER DEFAULT(0)
            ,CATEGORYID NUMBER
            ,PCONDITION VARCHAR2(20) CHECK(PCONDITION IN('중고', '새상품'))
            ,BUYSTATUS  VARCHAR2(50) 
            ,PRICE      NUMBER
            ,DEALMETHOD VARCHAR2(20) CHECK(DEALMETHOD IN('직거래', '택배거래'))
            ,CONSTRAINT BOARD_ACCOUNTID_FK FOREIGN KEY(ACCOUNTID) REFERENCES ACCOUNT(ACCOUNTID) ON DELETE CASCADE
            ,CONSTRAINT BOARD_CATEGORYID_FK FOREIGN KEY(CATEGORYID) REFERENCES CATEGORY(CATEGORYID)
);

CREATE SEQUENCE BOARD_SEQ NOCACHE;

SELECT * FROM BOARD;
DROP TABLE BOARD;


-- 테이블을 다시 만들지 않고 해당 제약조건만 수정하는 쿼리

-- 1. 아래 쿼리로 해당 제약조건을 삭제한 후
ALTER TABLE BOARD DROP CONSTRAINT BOARD_ACCOUNTID_FK;
-- 2. ON DELETE CASCADE를 적용시킨 제약조건을 다시 설정
ALTER TABLE BOARD 
ADD CONSTRAINT BOARD_ACCOUNTID_FK
FOREIGN KEY (ACCOUNTID) 
REFERENCES ACCOUNT (ACCOUNTID) 
ON DELETE CASCADE;
-- 3. 잘 설정되었는지 확인
SELECT *
  FROM USER_CONSTRAINTS
 WHERE TABLE_NAME = 'BOARD';
