/**
 *  BOARD_STATICS 스키마
 */

CREATE TABLE BOARD_STATICS(
            BOARDSTATID NUMBER PRIMARY KEY
           ,ACCOUNTID   VARCHAR2(50)
           ,BID         NUMBER
           ,VIEWED      VARCHAR2(1) CHECK(VIEWED IN('Y','N'))
           ,LATEST_VIEWED_DATE DATE
           ,CONSTRAINT BAORD_STATICS_BID_FK FOREIGN KEY(BID) REFERENCES BOARD(BID) ON DELETE CASCADE
);

CREATE SEQUENCE BOARD_STATICS_SEQ NOCACHE;

-- BID_FK도 ON DLETE CASCADE 추가 해야됨 9.24

SELECT * FROM BOARD_STATICS;
DROP TABLE BOARD_STATICS;


-- 테이블을 다시 만들지 않고 해당 제약조건만 수정하는 쿼리

-- 1. 아래 쿼리로 해당 제약조건을 삭제한 후
ALTER TABLE BOARD_STATICS DROP CONSTRAINT BAORD_STATICS_BID_FK;

-- 2. ON DELETE CASCADE를 적용시킨 제약조건을 다시 설정

ALTER TABLE BOARD_STATICS 
ADD CONSTRAINT BAORD_STATICS_BID_FK
FOREIGN KEY (BID) 
REFERENCES BOARD (BID) 
ON DELETE CASCADE;

-- 3. 잘 설정되었는지 확인
SELECT *
  FROM USER_CONSTRAINTS
 WHERE TABLE_NAME = 'BOARD_STATICS';