/**
 *  CATEGORY 스키마
 */

CREATE TABLE CATEGORY(
             CATEGORYID NUMBER PRIMARY KEY
            ,CATEGORYNAME VARCHAR2(500)
);

CREATE SEQUENCE CATEGORY_SEQ NOCACHE;

SELECT * FROM CATEGORY;
DROP TABLE CATEGORY;